name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Login - Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push no Docker Hub
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/microservice_products:$GITHUB_RUN_NUMBER
        docker tag ${{ secrets.DOCKER_USERNAME }}/microservice_products:$GITHUB_RUN_NUMBER ${{ secrets.DOCKER_USERNAME }}/microservice_products:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/microservice_products:$GITHUB_RUN_NUMBER
        docker push ${{ secrets.DOCKER_USERNAME }}/microservice_products:latest
