name: Docker Image CI

on:
  push:
    branches:
    - main
    tags:
    - 'v*'

jobs:
  checkout_code:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  build_and_push:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: DockerHub

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Login - Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push to Docker Hub
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "Building Docker image with tag: $TAG_NAME"
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/microservice_products:${TAG_NAME}
        docker push ${{ secrets.DOCKER_USERNAME }}/microservice_products:${TAG_NAME}
